// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/UseIncenseResponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from POGOProtos/Networking/Responses/UseIncenseResponse.proto</summary>
  public static partial class UseIncenseResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Networking/Responses/UseIncenseResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UseIncenseResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjhQT0dPUHJvdG9zL05ldHdvcmtpbmcvUmVzcG9uc2VzL1VzZUluY2Vuc2VS",
            "ZXNwb25zZS5wcm90bxIfUE9HT1Byb3Rvcy5OZXR3b3JraW5nLlJlc3BvbnNl",
            "cxomUE9HT1Byb3Rvcy9JbnZlbnRvcnkvQXBwbGllZEl0ZW0ucHJvdG8ihwIK",
            "ElVzZUluY2Vuc2VSZXNwb25zZRJKCgZyZXN1bHQYASABKA4yOi5QT0dPUHJv",
            "dG9zLk5ldHdvcmtpbmcuUmVzcG9uc2VzLlVzZUluY2Vuc2VSZXNwb25zZS5S",
            "ZXN1bHQSOgoPYXBwbGllZF9pbmNlbnNlGAIgASgLMiEuUE9HT1Byb3Rvcy5J",
            "bnZlbnRvcnkuQXBwbGllZEl0ZW0iaQoGUmVzdWx0EgsKB1VOS05PV04QABIL",
            "CgdTVUNDRVNTEAESGgoWSU5DRU5TRV9BTFJFQURZX0FDVElWRRACEhUKEU5P",
            "TkVfSU5fSU5WRU5UT1JZEAMSEgoOTE9DQVRJT05fVU5TRVQQBGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Inventory.AppliedItemReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.UseIncenseResponse), global::POGOProtos.Networking.Responses.UseIncenseResponse.Parser, new[]{ "Result", "AppliedIncense" }, null, new[]{ typeof(global::POGOProtos.Networking.Responses.UseIncenseResponse.Types.Result) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UseIncenseResponse : pb::IMessage<UseIncenseResponse> {
    private static readonly pb::MessageParser<UseIncenseResponse> _parser = new pb::MessageParser<UseIncenseResponse>(() => new UseIncenseResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UseIncenseResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.UseIncenseResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UseIncenseResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UseIncenseResponse(UseIncenseResponse other) : this() {
      result_ = other.result_;
      AppliedIncense = other.appliedIncense_ != null ? other.AppliedIncense.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UseIncenseResponse Clone() {
      return new UseIncenseResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::POGOProtos.Networking.Responses.UseIncenseResponse.Types.Result result_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Networking.Responses.UseIncenseResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "applied_incense" field.</summary>
    public const int AppliedIncenseFieldNumber = 2;
    private global::POGOProtos.Inventory.AppliedItem appliedIncense_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Inventory.AppliedItem AppliedIncense {
      get { return appliedIncense_; }
      set {
        appliedIncense_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UseIncenseResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UseIncenseResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (!object.Equals(AppliedIncense, other.AppliedIncense)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (appliedIncense_ != null) hash ^= AppliedIncense.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (appliedIncense_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AppliedIncense);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (appliedIncense_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AppliedIncense);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UseIncenseResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      if (other.appliedIncense_ != null) {
        if (appliedIncense_ == null) {
          appliedIncense_ = new global::POGOProtos.Inventory.AppliedItem();
        }
        AppliedIncense.MergeFrom(other.AppliedIncense);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            result_ = (global::POGOProtos.Networking.Responses.UseIncenseResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            if (appliedIncense_ == null) {
              appliedIncense_ = new global::POGOProtos.Inventory.AppliedItem();
            }
            input.ReadMessage(appliedIncense_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the UseIncenseResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("INCENSE_ALREADY_ACTIVE")] IncenseAlreadyActive = 2,
        [pbr::OriginalName("NONE_IN_INVENTORY")] NoneInInventory = 3,
        [pbr::OriginalName("LOCATION_UNSET")] LocationUnset = 4,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
