namespace PoGo.PokeMobBot.Logic.Enums
{
    public enum MainRpc
    {
        BotFailure,
        Log,
        Error,
        PokeStops,
        Pokemons,
        PokemonsWild,
        PokemonMapRemove,
        PokestopSetLure,
        PlayerLocation,
        PokemonList,
        ItemList,
        NewVersion,
        ItemNew,
        PokemonNew,
        RouteNext,
        ItemRemove,
        PokemonLost,
        PokemonUpdate,
        TeamSet,
        PokemonFav,
        Profile,
        ForceMoveDone,
        GymPoke,
        PokestopsOpt,
        Lvl,
        PokestopInfo,
        PokeActionDone,
        ItemUsed,
        Buddy,
        Challenge
    }
}
